image:
  repository: payment-service
  tag: s2
  pullPolicy: IfNotPresent

service:
  port: 8081

database:
  url: jdbc:postgresql://postgres.db.svc.cluster.local:5432/lab?currentSchema=payments
  username: lab
  password: changeme

otel:
  serviceName: payment-service
  endpoint: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318
  protocol: http/protobuf

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 800m
    memory: 768Mi

serviceMonitor:
  release: kube-prometheus-stack
  interval: 30s
