#!/usr/bin/env bash
# archive-integrity-chain: the 0.9.25 hash chain over the daemon's per-window
# NDJSON archive, read back through `disclose`.
#
# Until 0.9.25 the integrity story stopped at the published document: the
# content_hash and the cosign signature proved a report had not moved since
# generation, while the windows it was aggregated FROM carried nothing. Editing
# one before running `disclose` produced a coherent report with a valid hash.
# Each archive line now records the hash of {ts, report, prev, seq}, and
# `disclose` publishes the verdict under `integrity.trace_integrity_chain`.
#
# Assertions (see README.md):
#   A  an intact archive: breaks = 0, windows_verified == the number of windows.
#   B  one window edited in place: breaks = 1, and the report is still produced
#      (a break is published, not fatal).
#   C  an archive written before chaining existed: windows_unchained = N,
#      breaks = 0 — no accusation of tampering on a pre-chaining file.
#   D  the `hash` field REMOVED from a line after the chain has started: counted
#      as a break, not as a benign pre-chaining line. Without this rule,
#      stripping the field would be a way to rewrite a window and still publish
#      zero breaks.
#   E  an ungraceful kill (SIGKILL) mid-write, then a restart: the daemon reads
#      the last hash back before appending, so a restart is not tampering.
#      breaks = 0.
#   F  a deterministically truncated tail, then a restart: the torn line counts
#      as a LOST window, never as a break. breaks = 0 and windows_verified is
#      one short of the physical line count.
#
# E and F are the same guarantee from two angles. E is the operational shape
# (kill -9 a daemon that is writing) and cannot promise it will tear a line;
# F cuts the last line in half by hand, which is the case the product fixed at
# the very end of the branch and had only ever run under unit tests.
#
# Self-contained: no cluster, no Docker. Needs the local release binary and
# python3. The archive is generated by a real daemon rather than committed as a
# fixture, so the chain always matches the binary under test.
set -uo pipefail

SCENARIO="archive-integrity-chain"
REPORT="/tmp/scenario-${SCENARIO}-report.md"
# Short on purpose: the daemon's JSON socket lives here and a Unix socket path
# is capped near 104 bytes, which a longer working directory blows past.
TMP_DIR="/tmp/${SCENARIO}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LAB_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ORG_CONFIG="${LAB_ROOT}/scenarios/disclose/fixtures/org-config.toml"

PERF_SENTINEL_REPO_PATH="${PERF_SENTINEL_REPO_PATH:-${HOME}/RustroverProjects/perf-sentinel}"
PERF_SENTINEL_LOCAL_BIN="${PERF_SENTINEL_LOCAL_BIN:-${PERF_SENTINEL_REPO_PATH}/target/release/perf-sentinel}"
HTTP_PORT="${AIC_HTTP_PORT:-14530}"
GRPC_PORT="${AIC_GRPC_PORT:-14531}"
# The daemon archives one window per eviction cycle that carried traffic, so
# trace_ttl_ms sets the window cadence. 1s keeps the whole scenario short.
TTL_MS="${AIC_TTL_MS:-1000}"

rm -rf "${TMP_DIR}"
mkdir -p "${TMP_DIR}"

color_blue()  { printf "\033[34m%s\033[0m\n" "$*"; }
color_green() { printf "\033[32m%s\033[0m\n" "$*"; }
color_red()   { printf "\033[31m%s\033[0m\n" "$*"; }
step() { color_blue "==> $*"; }
ok()   { color_green "    ok: $*"; }
die()  { color_red   "    error: $*"; exit 1; }

DAEMON_PID=""
SEED_PID=""
cleanup() {
  [ -n "${SEED_PID}" ] && kill "${SEED_PID}" 2>/dev/null
  [ -n "${DAEMON_PID}" ] && kill -TERM "${DAEMON_PID}" 2>/dev/null
  wait 2>/dev/null
  return 0
}
trap cleanup EXIT

RESULTS=()
FAILS=0
assert_pass() { RESULTS+=("$1|PASS|$2"); color_green "    PASS $1: $2"; }
assert_fail() { RESULTS+=("$1|FAIL|$2"); color_red   "    FAIL $1: $2"; FAILS=$((FAILS + 1)); }

[ -x "${PERF_SENTINEL_LOCAL_BIN}" ] \
  || die "no local binary at ${PERF_SENTINEL_LOCAL_BIN} (cargo build --release first)"
[ -f "${ORG_CONFIG}" ] || die "missing org config ${ORG_CONFIG}"
BIN_VERSION="$("${PERF_SENTINEL_LOCAL_BIN}" --version | awk '{print $2}')"
step "binary ${PERF_SENTINEL_LOCAL_BIN} (${BIN_VERSION})"

# --- daemon plumbing --------------------------------------------------------
# [green] enabled is mandatory for the archive: the daemon refuses the pairing
# otherwise, since an archive of windows with no energy makes `disclose`
# meaningless.
write_config() {  # $1 = archive path
  cat > "${TMP_DIR}/cfg.toml" <<EOF
[green]
enabled = true
default_region = "FR"

[daemon]
listen_address = "127.0.0.1"
listen_port_http = ${HTTP_PORT}
listen_port_grpc = ${GRPC_PORT}
api_enabled = true
json_socket = "${TMP_DIR}/s"
trace_ttl_ms = ${TTL_MS}
environment = "staging"

[daemon.ack]
enabled = false

[daemon.archive]
path = "$1"

[detection]
n_plus_one_min_occurrences = 5
EOF
}

cat > "${TMP_DIR}/seed.py" <<'PY'
import json, socket, sys, time
from datetime import datetime, timezone

sock_path, interval = sys.argv[1], float(sys.argv[2])
n = 0
while True:
    now = datetime.now(timezone.utc)
    ts = now.strftime("%Y-%m-%dT%H:%M:%S.") + f"{now.microsecond // 1000:03d}Z"
    tid = f"aic{n:029d}"
    # 8 sibling SELECTs under one endpoint clears n_plus_one_min_occurrences,
    # so every window carries a finding and an avoidable share to archive.
    events = [{
        "timestamp": ts, "trace_id": tid, "span_id": f"s{i:015d}",
        "parent_span_id": "s000000000000000", "service": "shop-svc",
        "cloud_region": "eu-west-3",
        "type": "sql", "operation": "SELECT",
        "target": f"SELECT * FROM items WHERE order_id = {i}",
        "duration_us": 1500,
        "source": {"endpoint": "GET /orders", "method": "OrderService::list"},
    } for i in range(1, 9)]
    try:
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(sock_path)
        s.sendall((json.dumps(events) + "\n").encode())
        s.close()
    except OSError:
        pass
    n += 1
    time.sleep(interval)
PY

start_daemon() {  # $1 = log file
  "${PERF_SENTINEL_LOCAL_BIN}" watch --config "${TMP_DIR}/cfg.toml" > "${TMP_DIR}/$1" 2>&1 &
  DAEMON_PID=$!
  for _ in $(seq 1 40); do
    [ -S "${TMP_DIR}/s" ] && return 0
    kill -0 "${DAEMON_PID}" 2>/dev/null || return 1
    sleep 0.25
  done
  return 1
}

start_seeding() { python3 "${TMP_DIR}/seed.py" "${TMP_DIR}/s" "${1:-0.2}" >/dev/null 2>&1 & SEED_PID=$!; }
stop_seeding()  { [ -n "${SEED_PID}" ] && kill "${SEED_PID}" 2>/dev/null; SEED_PID=""; }
stop_daemon()   { [ -n "${DAEMON_PID}" ] && { kill -TERM "${DAEMON_PID}" 2>/dev/null; wait "${DAEMON_PID}" 2>/dev/null; }; DAEMON_PID=""; }

# A custom period wide around today, so a run started minutes before a month or
# quarter boundary never lands on an empty period.
PERIOD_FROM="$(python3 -c "
import datetime as d
print((d.datetime.now(d.timezone.utc) - d.timedelta(days=120)).date())")"
PERIOD_TO="$(python3 -c "
import datetime as d
print((d.datetime.now(d.timezone.utc) + d.timedelta(days=120)).date())")"

# Disclose one archive and print the four chain counters, or "ERROR".
chain_of() {  # $1 = archive, $2 = output report
  "${PERF_SENTINEL_LOCAL_BIN}" disclose --intent internal --confidentiality internal \
    --period-type custom --from "${PERIOD_FROM}" --to "${PERIOD_TO}" \
    --input "$1" --org-config "${ORG_CONFIG}" --output "$2" \
    > "${TMP_DIR}/$(basename "$2" .json).log" 2>&1 || { echo "ERROR"; return 1; }
  python3 -c "
import json, sys
try:
    c = json.load(open('$2'))['integrity']['trace_integrity_chain'] or {}
except Exception as e:
    print('ERROR'); sys.exit(0)
print(c.get('windows_verified'), c.get('windows_unchained'), c.get('breaks'), c.get('breaks_outside_period'))"
}

# --- generate one real chained archive --------------------------------------
step "generating a chained archive from a live daemon"
BASE="${TMP_DIR}/base.ndjson"
write_config "${BASE}"
start_daemon "d-base.log" || die "daemon did not start: $(tail -3 "${TMP_DIR}/d-base.log")"
start_seeding 0.2
sleep 12
stop_seeding
stop_daemon
LINES="$(grep -c . "${BASE}" 2>/dev/null || echo 0)"
[ "${LINES}" -ge 5 ] || die "only ${LINES} archived window(s), need at least 5 (see ${TMP_DIR}/d-base.log)"
ok "${LINES} chained windows in ${BASE}"

# --- A: intact --------------------------------------------------------------
step "A: an intact archive verifies clean"
read -r A_VER A_UNC A_BRK A_OUT <<< "$(chain_of "${BASE}" "${TMP_DIR}/rep-a.json")"
if [ "${A_BRK}" = "0" ] && [ "${A_VER}" = "${LINES}" ] && [ "${A_UNC}" = "0" ]; then
  assert_pass "A" "breaks=0, windows_verified=${A_VER} == ${LINES} archived windows, unchained=0"
else
  assert_fail "A" "verified=${A_VER} (want ${LINES}), unchained=${A_UNC}, breaks=${A_BRK}, outside=${A_OUT}"
fi

# --- B / C / D: three doctored copies ---------------------------------------
step "building the doctored archives"
python3 - "${BASE}" "${TMP_DIR}" <<'PY'
import json, pathlib, sys

src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
lines = [l for l in src.read_text().splitlines() if l.strip()]
mid = len(lines) // 2

# B: rewrite one window's payload, leave its stated hash untouched. This is the
# edit the chain exists to catch: the line still parses and still claims a hash.
b = list(lines)
o = json.loads(b[mid])
o["report"]["traces_analyzed"] = 999999
b[mid] = json.dumps(o, separators=(",", ":"))
(out / "b-edited.ndjson").write_text("\n".join(b) + "\n")

# C: the shape an archive written before 0.9.25 has — no prev, no seq, no hash.
c = [json.dumps({"ts": json.loads(l)["ts"], "report": json.loads(l)["report"]},
                separators=(",", ":")) for l in lines]
(out / "c-legacy.ndjson").write_text("\n".join(c) + "\n")

# D: strip the hash of ONE line, after the file's chain has started.
d = list(lines)
o = json.loads(d[mid])
o.pop("hash", None)
d[mid] = json.dumps(o, separators=(",", ":"))
(out / "d-stripped.ndjson").write_text("\n".join(d) + "\n")
print(f"edited/stripped line {mid + 1} of {len(lines)}")
PY

step "B: one edited window is published as exactly one break"
read -r B_VER B_UNC B_BRK B_OUT <<< "$(chain_of "${TMP_DIR}/b-edited.ndjson" "${TMP_DIR}/rep-b.json")"
if [ "${B_BRK}" = "1" ] && [ -s "${TMP_DIR}/rep-b.json" ]; then
  assert_pass "B" "breaks=1, verified=${B_VER}, and the report was still produced (a break is published, not fatal)"
else
  assert_fail "B" "breaks=${B_BRK} (want 1), verified=${B_VER}, report present=$([ -s "${TMP_DIR}/rep-b.json" ] && echo yes || echo no)"
fi

step "C: a pre-chaining archive is not accused of tampering"
read -r C_VER C_UNC C_BRK C_OUT <<< "$(chain_of "${TMP_DIR}/c-legacy.ndjson" "${TMP_DIR}/rep-c.json")"
if [ "${C_BRK}" = "0" ] && [ "${C_UNC}" = "${LINES}" ]; then
  assert_pass "C" "windows_unchained=${C_UNC} == all ${LINES} windows, breaks=0, verified=${C_VER}"
else
  assert_fail "C" "unchained=${C_UNC} (want ${LINES}), breaks=${C_BRK} (want 0), verified=${C_VER}"
fi

step "D: a hash removed after the chain started is a break, not a legacy line"
read -r D_VER D_UNC D_BRK D_OUT <<< "$(chain_of "${TMP_DIR}/d-stripped.ndjson" "${TMP_DIR}/rep-d.json")"
if [ "${D_BRK}" = "1" ] && [ "${D_UNC}" = "0" ]; then
  assert_pass "D" "breaks=1, unchained=0 — stripping the field is not a way to publish zero breaks"
else
  assert_fail "D" "breaks=${D_BRK} (want 1), unchained=${D_UNC} (want 0), verified=${D_VER}"
fi

# --- E: SIGKILL then restart ------------------------------------------------
step "E: SIGKILL mid-write, then a restart, is not tampering"
KILLED="${TMP_DIR}/killed.ndjson"
write_config "${KILLED}"
start_daemon "d-kill1.log" || die "daemon did not start for E"
start_seeding 0.15
sleep 6
kill -KILL "${DAEMON_PID}" 2>/dev/null
wait "${DAEMON_PID}" 2>/dev/null
DAEMON_PID=""
E_AFTER_KILL="$(grep -c . "${KILLED}" 2>/dev/null || echo 0)"
start_daemon "d-kill2.log" || die "daemon did not restart for E"
sleep 6
stop_seeding
stop_daemon
E_LINES="$(grep -c . "${KILLED}" 2>/dev/null || echo 0)"
read -r E_VER E_UNC E_BRK E_OUT <<< "$(chain_of "${KILLED}" "${TMP_DIR}/rep-e.json")"
if [ "${E_BRK}" = "0" ] && [ "${E_LINES}" -gt "${E_AFTER_KILL}" ]; then
  assert_pass "E" "killed at ${E_AFTER_KILL} windows, restarted and grew to ${E_LINES}, breaks=0 (verified=${E_VER})"
else
  assert_fail "E" "breaks=${E_BRK} (want 0), ${E_AFTER_KILL} -> ${E_LINES} windows, verified=${E_VER}"
fi

# --- F: a torn tail is a lost window, not a break ---------------------------
step "F: a truncated tail counts as a lost window, never as a break"
TORN="${TMP_DIR}/torn.ndjson"
write_config "${TORN}"
start_daemon "d-torn1.log" || die "daemon did not start for F"
start_seeding 0.2
sleep 8
stop_seeding
stop_daemon
F_BEFORE="$(grep -c . "${TORN}" 2>/dev/null || echo 0)"
[ "${F_BEFORE}" -ge 3 ] || die "F needs at least 3 windows before tearing, got ${F_BEFORE}"
# Cut the last line in half: what a crash between two write syscalls leaves.
python3 - "${TORN}" <<'PY'
import pathlib, sys
p = pathlib.Path(sys.argv[1])
lines = [l for l in p.read_bytes().split(b"\n") if l.strip()]
last = lines[-1]
p.write_bytes(b"\n".join(lines[:-1]) + b"\n" + last[: len(last) // 2])
print(f"tore the last line at {len(last) // 2}/{len(last)} bytes, no trailing newline")
PY
start_daemon "d-torn2.log" || die "daemon did not restart for F"
start_seeding 0.2
sleep 8
stop_seeding
stop_daemon
F_PHYS="$(grep -c . "${TORN}" 2>/dev/null || echo 0)"
read -r F_VER F_UNC F_BRK F_OUT <<< "$(chain_of "${TORN}" "${TMP_DIR}/rep-f.json")"
if [ "${F_BRK}" = "0" ] && [ "${F_UNC}" = "0" ] && [ "${F_VER}" -lt "${F_PHYS}" ]; then
  assert_pass "F" "breaks=0 across the tear; ${F_VER} windows verified out of ${F_PHYS} physical lines — the torn one is lost, not accused"
else
  assert_fail "F" "breaks=${F_BRK} (want 0), unchained=${F_UNC} (want 0), verified=${F_VER} vs ${F_PHYS} physical lines"
fi

# --- verdict ----------------------------------------------------------------
step "Summary"
verdict="PASS"
[ "${FAILS}" -gt 0 ] && verdict="FAIL"
{
  echo "# Scenario: ${SCENARIO}"
  echo ""
  echo "- Binary: ${PERF_SENTINEL_LOCAL_BIN} (${BIN_VERSION})"
  echo "- Archive generated live: ${LINES} chained windows"
  echo ""
  echo "| id | result | detail |"
  echo "|---|---|---|"
  for r in "${RESULTS[@]}"; do
    IFS='|' read -r id res msg <<< "${r}"
    echo "| ${id} | ${res} | ${msg} |"
  done
  echo ""
  echo "Verdict: **${verdict}**"
} > "${REPORT}"

if [ "${verdict}" = "PASS" ]; then
  color_green "PASS — report at ${REPORT}"
  exit 0
fi
color_red "FAIL (${FAILS}) — report at ${REPORT}"
exit 1
