[package]
name = "diesel-svc"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
diesel = { version = "=2.3.12", features = ["postgres", "r2d2"] }
lapin = "=4.10.0"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json"] }
reqwest-middleware = "0.5"
reqwest-tracing = { version = "0.7", features = ["opentelemetry_0_32"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
tower-http = { version = "0.6", features = ["trace"] }
axum-tracing-opentelemetry = "0.38"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.33"
opentelemetry = "0.32"
opentelemetry_sdk = "0.32"
opentelemetry-otlp = { version = "0.32", features = ["http-proto", "reqwest-blocking-client"] }

[dev-dependencies]
tower = { version = "=0.5.3", features = ["util"] }

[profile.release]
strip = true
lto = true
