#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 1 ]]; then
    echo "usage: $(basename "$0") <services/django-svc|services/fastapi-svc>" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_DIR="${1%/}"
case "${SERVICE_DIR}" in
    services/django-svc|services/fastapi-svc) ;;
    *)
        echo "unsupported Python service: ${SERVICE_DIR}" >&2
        exit 2
        ;;
esac

LOCK="${REPO_ROOT}/${SERVICE_DIR}/requirements.lock"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/perf-python-lock.XXXXXX")"
trap 'rm -rf "${TMP}"' EXIT

docker run --rm \
    --volume "${REPO_ROOT}/${SERVICE_DIR}:/service:ro" \
    --volume "${TMP}:/out" \
    --workdir /service \
    python:3.14-slim-bookworm@sha256:23c59390fc717bf09f9336908199a0ae75d9c4264bf296123f94ad772fea3b52 \
    sh -ec '
        python -m pip install --disable-pip-version-check --no-cache-dir --quiet pip==25.3 pip-tools==7.6.0 >/dev/null 2>&1
        python -m piptools compile --generate-hashes --strip-extras --no-header \
            --output-file=/out/requirements.body requirements.txt >/dev/null 2>&1
        sha256sum requirements.txt | cut -d " " -f 1 > /out/requirements.sha256
    '

SOURCE_SHA="$(tr -d '\n' < "${TMP}/requirements.sha256")"
{
    printf '# Generated by scripts/generate-python-lock.sh\n'
    printf '# Regenerate from the repository root:\n'
    printf '# ./scripts/generate-python-lock.sh %s\n' "${SERVICE_DIR}"
    printf '# requirements-sha256: %s\n\n' "${SOURCE_SHA}"
    cat "${TMP}/requirements.body"
} > "${LOCK}"
