apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: perf-sentinel-lab
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
