apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Values.serviceMonitor.release }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: perf-sentinel-lab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
